// Generated by Wrangler on Thu May 16 2024 14:39:35 GMT-0600 (Mountain Daylight Time)
// by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
  MY_VAR: "my-variable";
  DB: D1Database;
}

type Bindings = {
  [key in keyof CloudflareBindings]: CloudflareBindings[key];
};
